name: Release Artifact

env:
  NODE_VERSION: 16.14

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build-package

      - run: |
          echo @transmitsecurity:https://npm.pkg.github.com/ > dist/ngx-ts-riskid/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> dist/ngx-ts-riskid/.npmrc

      - run: yarn publish --access=public
        working-directory: ./dist/ngx-ts-riskid
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive failure data
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: failure-data
          path: |
            /home/runner/.npm/_logs
